server:
  port: ${PORT_TO_EXPOSE:8075}
spring:
  application:
    name: client-app
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_READING_DUP_TREE_KEY: true

logging:
  level:
    ROOT: INFO
    net.feign.demo: DEBUG
    org.springframework: ERROR
    com.netflix: DEBUG

feign:
  client:
    config:
      feignName:
        connectTimeout: 10000
        readTimeout: 50000
        loggerLevel: full
        errorDecoder: net.feign.demo.CustomFeignErrorDecoder
        decode404: false

client-app:
  ribbon:
    eureka:
      enabled: true
      client:
        fetchRegistry: true
    listOfServers: http://localhost:8085

hystrix:
  threadpool.default.coreSize: "20"
  threadpool.default.maxQueueSize: "500000"
  threadpool.default.keepAliveTimeMinutes: "2"
  threadpool.default.queueSizeRejectionThreshold: "500000"
  command:
    default:
      fallback.isolation.semaphore.maxConcurrentRequests: "20"
      execution:
        timeout:
          enabled: "false"
        isolation:
          strategy: "THREAD"
          thread:
            timeoutInMilliseconds: "30000"
